name: split_eth_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  archive: ^3.6.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  get_it: ^7.7.0
  go_router: ^14.2.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.2
  web3dart: ^2.7.3
  smartcontracts:
    git:
      url: https://github.com/citizenwallet/smartcontracts.git
      ref: v0.0.106

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    # assets that our app loads
    - lib/assets/config.json
    - lib/assets/group_factory.abi.json
    - lib/assets/group.abi.json
    # junk to make Kevin's code compile, probably not used
    - packages/smartcontracts/contracts/external/CardFactory.abi.json
    - packages/smartcontracts/contracts/standards/ERC20.abi.json
    - packages/smartcontracts/contracts/accounts/TokenEntryPoint.abi.json
    - packages/smartcontracts/contracts/accounts/Account.abi.json
    - packages/smartcontracts/contracts/accounts/AccountFactory.abi.json
    - packages/smartcontracts/contracts/apps/Profile.abi.json
